/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "adder_subtractor.v:1.1-60.10" *)
module adder_subtractor(A, B, Cin, Y, Z, Cout);
  (* src = "adder_subtractor.v:2.13-2.14" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "adder_subtractor.v:2.15-2.16" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "adder_subtractor.v:7.11-7.12" *)
  wire [2:0] C;
  (* src = "adder_subtractor.v:3.7-3.10" *)
  input Cin;
  wire Cin;
  (* src = "adder_subtractor.v:5.8-5.12" *)
  output Cout;
  wire Cout;
  (* src = "adder_subtractor.v:4.14-4.15" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "adder_subtractor.v:4.16-4.17" *)
  output [3:0] Z;
  wire [3:0] Z;
  (* module_not_derived = 32'd1 *)
  (* src = "adder_subtractor.v:14.12-19.14" *)
  full_adder FA0 (
    .A(A[0]),
    .B(Y[0]),
    .C(Cin),
    .Carry(C[0]),
    .Sum(Z[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_subtractor.v:27.12-32.14" *)
  full_adder FA1 (
    .A(A[1]),
    .B(Y[1]),
    .C(C[0]),
    .Carry(C[1]),
    .Sum(Z[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_subtractor.v:40.12-45.14" *)
  full_adder FA2 (
    .A(A[2]),
    .B(Y[2]),
    .C(C[1]),
    .Carry(C[2]),
    .Sum(Z[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_subtractor.v:53.12-58.14" *)
  full_adder FA3 (
    .A(A[3]),
    .B(Y[3]),
    .C(C[2]),
    .Carry(Cout),
    .Sum(Z[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_subtractor.v:9.10-12.10" *)
  xor_gate x0 (
    .A(Cin),
    .B(B[0]),
    .Y(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_subtractor.v:22.10-25.10" *)
  xor_gate x1 (
    .A(Cin),
    .B(B[1]),
    .Y(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_subtractor.v:35.10-38.10" *)
  xor_gate x2 (
    .A(Cin),
    .B(B[2]),
    .Y(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_subtractor.v:48.10-51.10" *)
  xor_gate x3 (
    .A(Cin),
    .B(B[3]),
    .Y(Y[3])
  );
endmodule

(* src = "full_adder.v:1.1-12.10" *)
module full_adder(A, B, C, Sum, Carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "full_adder.v:2.7-2.8" *)
  input A;
  wire A;
  (* src = "full_adder.v:2.10-2.11" *)
  input B;
  wire B;
  (* src = "full_adder.v:2.13-2.14" *)
  input C;
  wire C;
  (* src = "full_adder.v:3.13-3.18" *)
  output Carry;
  wire Carry;
  (* src = "full_adder.v:3.8-3.11" *)
  output Sum;
  wire Sum;
  assign _00_ = _04_ | _03_;
  assign _01_ = C & B;
  assign Carry = _01_ | _00_;
  assign _02_ = B ^ A;
  assign Sum = _02_ ^ C;
  assign _03_ = B & A;
  assign _04_ = C & A;
endmodule

(* src = "xor_gate.v:1.1-5.10" *)
module xor_gate(A, B, Y);
  (* src = "xor_gate.v:2.7-2.8" *)
  input A;
  wire A;
  (* src = "xor_gate.v:2.10-2.11" *)
  input B;
  wire B;
  (* src = "xor_gate.v:3.8-3.9" *)
  output Y;
  wire Y;
  assign Y = B ^ A;
endmodule
